spring:
  application:
    name: jpa-examples
  datasource:
    url: 'jdbc:mysql://localhost:3306/jpatest?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'