spring:
  application:
    name: redis-example
  redis:
    host: localhost
    port: 6379
    database: 0
  cache:
    redis:
      cache-null-values: true
      time-to-live: 50000



logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'